### ISSUE TITLE
Image is missing in hero button 

### ISSUE THREAD

**Issue by gouravg8** [amanbairagi30/merged-n-share#8]
![Screenshot_2024-10-21-10-22-54-92_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/af1f5620-f76c-42a5-9a00-eb6331d24b26)

### Issue arising from this block of code(image part):
src/components/hero-buttons.tsx
https://github.com/amanbairagi30/merged-n-share/blob/81d4afe84d91fa5584846e70374269518a436e57/src/components/hero-buttons.tsx#L33

**Comment by amanbairagi30** [comment]
Hi @gouravg8 . 
On local . There seems to be no issue with this / any image 

But since this project is currently deployed on the vercel and my vercel Image optimization limits have been crossed 

So I feel it must be their issue , we can easily get rid of this issue by replacing next js image tag with native image tag

But thanks for pointing out this issue , 
Are you willing to raise PR for the same .?

**Comment by amanbairagi30** [comment]
Done
